#!/usr/bin/env bash
set -euo pipefail
set -x
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

yum install -y git gcc binutils
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
export HOME="/"
export NVM_DIR="/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm install 16
npm install -g npm@9.4.2
npm install -g aws-cdk

# git clone https://github.com/awslabs/kubernetes-iteration-toolkit.git
git clone https://github.com/bwagner5/kubernetes-iteration-toolkit.git
cd kubernetes-iteration-toolkit/infrastructure
git fetch --all
git checkout testing

npm install

cdk bootstrap
cdk deploy KITInfrastructure --no-rollback \
  --require-approval never \
  -c TestFluxRepoName="karpenter" \
  -c TestFluxRepoURL="https://github.com/aws/karpenter" \
  -c TestFluxRepoBranch="main" \
  -c TestFluxRepoPath="./test/infrastructure/clusters/test-infra" \
  -c TestNamespace="karpenter-tests" \
  -c TestServiceAccount="karpenter-tests"
