{
 "title": "Pod Statistic",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total number of Pods",
   "type": "timeseries",
   "description": "Total number of Pods",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum (karpenter_pods_state)" }
   ]
  },
  {
   "title": "Pod Distribution by AZ",
   "type": "piechart",
   "description": "Pod Distribution by AZ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (zone)(karpenter_pods_state)",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by Instance Type ",
   "type": "piechart",
   "description": "Pod Distribution by Instance Type ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instancetype)(karpenter_pods_state)",
     "legendFormat": "{{instancetype}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by Capacity Type",
   "type": "piechart",
   "description": "Pod Distribution by Capacity Type",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (capacitytype)(karpenter_pods_state)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by Namespaces",
   "type": "piechart",
   "description": "Pod Distribution by Namespaces",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace)(karpenter_pods_state)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by Phase",
   "type": "piechart",
   "description": "Pod Distribution by Phase",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase)(karpenter_pods_state)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by Node",
   "type": "piechart",
   "description": "Pod Distribution by Node",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node)(karpenter_pods_state)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by Owner",
   "type": "piechart",
   "description": "Pod Distribution by Owner",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (owner)(karpenter_pods_state)",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}