{
 "title": "Cluster Capacity",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "arch", "query": { "query": "label_values(arch)" } },
   { "name": "capacity_type", "query": { "query": "label_values(capacity_type)" } },
   { "name": "instance_type", "query": { "query": "label_values(instance_type)" } },
   { "name": "provisioner", "query": { "query": "label_values(provisioner)" } },
   { "name": "zone", "query": { "query": "label_values(zone)" } },
   { "name": "resource_type", "query": { "query": "label_values(resource_type)" } },
   { "name": "node_name", "query": { "query": "label_values(node_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Node Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "((karpenter_nodes_total_pod_requests{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"} or karpenter_nodes_allocatable*0 + karpenter_nodes_total_daemon_requests{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"} or karpenter_nodes_allocatable*0) *100) / karpenter_nodes_allocatable{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node Overcommitment",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "((karpenter_nodes_total_pod_limits{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"} or karpenter_nodes_allocatable*0 + karpenter_nodes_total_daemon_limits{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"} or karpenter_nodes_allocatable*0 ) *100) / karpenter_nodes_allocatable{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Cluster Residual Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (resource_type)(karpenter_nodes_allocatable{resource_type!=\"pods\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"} or karpenter_nodes_total_overhead{resource_type!=\"pods\"}*0 or karpenter_nodes_total_requests{resource_type!=\"pods\"}*0)- sum by (resource_type)(karpenter_nodes_total_overhead{resource_type!=\"pods\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"} or karpenter_nodes_allocatable{resource_type!=\"pods\"}*0 or karpenter_nodes_total_requests{resource_type!=\"pods\"}*0) - sum by (resource_type)(karpenter_nodes_total_requests{resource_type!=\"pods\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"} or karpenter_nodes_allocatable{resource_type!=\"pods\"}*0 or karpenter_nodes_total_overhead{resource_type!=\"pods\"}*0)",
     "legendFormat": "{{resource_type}}"
    },
    {
     "expr": "sum (karpenter_nodes_allocatable{resource_type=\"pods\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"}) - sum (karpenter_pods_state{})",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Current Node Metrics",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "karpenter_nodes_allocatable{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"}",
     "legendFormat": "Allocatable CPU"
    },
    {
     "expr": "karpenter_nodes_total_pod_requests{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"}",
     "legendFormat": "Requests CPU"
    },
    {
     "expr": "karpenter_nodes_total_daemon_requests{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"}",
     "legendFormat": "Requests CPU"
    },
    {
     "expr": "karpenter_nodes_total_pod_limits{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"}",
     "legendFormat": "Limits CPU"
    },
    {
     "expr": "karpenter_nodes_total_daemon_limits{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"}",
     "legendFormat": "Limits CPU"
    },
    {
     "expr": "karpenter_nodes_system_overhead{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"}",
     "legendFormat": "Overhead CPU"
    },
    {
     "expr": "((karpenter_nodes_total_pod_requests{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"} or karpenter_nodes_allocatable*0 + karpenter_nodes_total_daemon_requests{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"} or karpenter_nodes_allocatable*0) *100) / karpenter_nodes_allocatable{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"}",
     "legendFormat": "Utilization CPU"
    },
    {
     "expr": "((karpenter_nodes_total_pod_limits{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"} or karpenter_nodes_allocatable*0 + karpenter_nodes_total_daemon_limits{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"} or karpenter_nodes_allocatable*0 ) *100) / karpenter_nodes_allocatable{resource_type=\"$resource_type\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\", zone=~\"$zone\", node_name=~\"$node_name\"}",
     "legendFormat": "Overcommitment CPU"
    }
   ]
  }
 ]
}