{
 "title": "Controllers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(controller_runtime_reconcile_errors_total, controller)"
    }
   },
   { "name": "trailing", "label": "Trailing", "query": "30s,1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Displays information collected by the Kubernetes controller-runtime.\n\nSee the information icon of each panel for a description.\n\nSuggest improvements and additions [here](https://github.com/aws/karpenter/issues/new?labels=dashboard)."
   }
  },
  {
   "title": "Items in Work Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workqueue_depth{name=\"$controller\"}",
     "legendFormat": "items"
    }
   ]
  },
  {
   "title": "Reconcilitions per minute",
   "type": "graph",
   "description": "The rate of completed reconciliations per minute broken out by result status.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{controller=\"$controller\"}[$trailing]) * 60",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Reconciliation duration",
   "type": "heatmap",
   "description": "Aggregates the duration of the reconciliation process.\n\nThe color of each \"bucket\" is a visual clue to the number of reconciliations that completed within that time range.\n\nMouse-over a bucket to display exact values.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_time_seconds_bucket{controller=\"$controller\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}