{
 "title": "Capacity / At a Glance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "provisioner",
    "label": "Provisioner",
    "query": {
     "query": "label_values(karpenter_capacity_node_count, provisioner)"
    }
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": {
     "query": "label_values(karpenter_capacity_ready_node_count, zone)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Displays information about the Nodes associated with provisioner \"$provisioner\".  The *Overview* row displays current counts across all zones.  Rows with zone specific counts will automatically be added for each observed zone within the selected time range.\n\nSee the information icon of each panel for a description.\n\nSuggest improvements and additions [here](https://github.com/aws/karpenter/issues/new?labels=dashboard)."
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Reporting as ready",
   "type": "gauge",
   "description": "Percentage of capacity reporting as \"ready\".",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_capacity_ready_node_count{provisioner=\"$provisioner\"}) / sum(karpenter_capacity_node_count{provisioner=\"$provisioner\"})",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Ready capacity by zone",
   "type": "piechart",
   "description": "Compares capacity that is \"ready\" in each zone.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(zone) (karpenter_capacity_ready_node_count{provisioner=\"$provisioner\"}) > 0",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Ready capacity by instance type",
   "type": "piechart",
   "description": "Compares capacity reporting as \"ready\" by instance type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instancetype) (karpenter_capacity_ready_node_instancetype_count{provisioner=\"$provisioner\"}) > 0",
     "legendFormat": "{{instancetype}}"
    }
   ]
  },
  {
   "title": "Ready capacity by node architecture",
   "type": "piechart",
   "description": "Comparison of capacity reporting as \"ready\" by hardware architecture.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(arch) (karpenter_capacity_ready_node_arch_count{provisioner=\"$provisioner\"}) > 0",
     "legendFormat": "{{arch}}"
    }
   ]
  },
  { "title": "Zone $zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "zone" },
  {
   "title": "Ready capacity by instance type",
   "type": "piechart",
   "description": "Compares capacity reporting as \"ready\" by instance type.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "karpenter_capacity_ready_node_instancetype_count{provisioner=\"$provisioner\", zone=\"$zone\"} > 0",
     "legendFormat": "{{instancetype}}"
    }
   ]
  },
  {
   "title": "Ready capacity by node architecture",
   "type": "piechart",
   "description": "Comparison of capacity reporting as \"ready\" by hardware architecture.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "karpenter_capacity_ready_node_arch_count{provisioner=\"$provisioner\", zone=\"$zone\"} > 0",
     "legendFormat": "{{arch}}"
    }
   ]
  }
 ]
}