{
 "title": "Pod Statistic",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "zone", "query": { "query": "label_values(zone)" } },
   { "name": "owner", "query": { "query": "label_values(owner)" } },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "node", "query": { "query": "label_values(node)" } },
   { "name": "instance_type", "query": { "query": "label_values(instance_type)" } },
   { "name": "phase", "query": { "query": "label_values(phase)" } },
   { "name": "capacity_type", "query": { "query": "label_values(capacity_type)" } },
   { "name": "arch", "query": { "query": "label_values(arch)" } },
   { "name": "provisioner", "query": { "query": "label_values(provisioner)" } }
  ]
 },
 "panels": [
  {
   "title": "Total number of Pods",
   "type": "timeseries",
   "description": "Total number of Pods",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (karpenter_pods_state{namespace=~\"$namespace\", node=~\"$node\", zone=~\"$zone\", instance_type=~\"$instance_type\",  owner=~\"$owner\",  phase=~\"$phase\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", provisioner=~\"$provisioner\"})",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "Pod Distribution by AZ",
   "type": "timeseries",
   "description": "Pod Distribution by AZ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (zone)(karpenter_pods_state{namespace=~\"$namespace\", node=~\"$node\", zone=~\"$zone\", instance_type=~\"$instance_type\",  owner=~\"$owner\",  phase=~\"$phase\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", provisioner=~\"$provisioner\"})",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by Namespaces",
   "type": "timeseries",
   "description": "Pod Distribution by Namespaces",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (namespace)(karpenter_pods_state{namespace=~\"$namespace\", node=~\"$node\", zone=~\"$zone\", instance_type=~\"$instance_type\",  owner=~\"$owner\",  phase=~\"$phase\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", provisioner=~\"$provisioner\"})"
    }
   ]
  },
  {
   "title": "Pod Distribution by Node",
   "type": "timeseries",
   "description": "Pod Distribution by Node",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (node)(karpenter_pods_state{namespace=~\"$namespace\", node=~\"$node\", zone=~\"$zone\", instance_type=~\"$instance_type\",  owner=~\"$owner\",  phase=~\"$phase\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", provisioner=~\"$provisioner\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by Instance Type",
   "type": "timeseries",
   "description": "Pod Distribution by Instance Type",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (instance_type)(karpenter_pods_state{namespace=~\"$namespace\", node=~\"$node\", zone=~\"$zone\", instance_type=~\"$instance_type\",  owner=~\"$owner\",  phase=~\"$phase\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", provisioner=~\"$provisioner\"})",
     "legendFormat": "{{instance_type}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by Phase",
   "type": "timeseries",
   "description": "Pod Distribution by Phase",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (phase)(karpenter_pods_state{namespace=~\"$namespace\", node=~\"$node\", zone=~\"$zone\", instance_type=~\"$instance_type\",  owner=~\"$owner\",  phase=~\"$phase\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", provisioner=~\"$provisioner\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by Capacity Type",
   "type": "timeseries",
   "description": "Pod Distribution by Capacity Type",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (capacity_type)(karpenter_pods_state{namespace=~\"$namespace\", node=~\"$node\", zone=~\"$zone\", instance_type=~\"$instance_type\",  owner=~\"$owner\",  phase=~\"$phase\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", provisioner=~\"$provisioner\"})",
     "legendFormat": "{{capacity_type}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by Owner",
   "type": "timeseries",
   "description": "Pod Distribution by Owner",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (owner)(karpenter_pods_state{namespace=~\"$namespace\", node=~\"$node\", zone=~\"$zone\", instance_type=~\"$instance_type\",  owner=~\"$owner\",  phase=~\"$phase\", arch=~\"$arch\", capacity_type=~\"$capacity_type\", provisioner=~\"$provisioner\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  }
 ]
}