{
 "title": "Cluster Capacity",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Cluster Residual CPU Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (karpenter_nodes_allocatable_cpu) - sum (karpenter_nodes_overheads_cpu) - sum (karpenter_nodes_totalrequests_cpu)"
    }
   ]
  },
  {
   "title": "Cluster Residual Memory Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (karpenter_nodes_allocatable_memory) - sum (karpenter_nodes_overheads_memory) - sum (karpenter_nodes_totalrequests_memory)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "karpenter_nodes_allocatable_cpu{}",
     "legendFormat": "Allocatable CPU"
    },
    {
     "expr": "karpenter_nodes_totalrequests_cpu{}",
     "legendFormat": "Requests CPU"
    },
    {
     "expr": "karpenter_nodes_totallimits_cpu{}",
     "legendFormat": "Limits CPU"
    },
    {
     "expr": "karpenter_nodes_overheads_cpu{}",
     "legendFormat": "Overhead CPU"
    },
    {
     "expr": "((karpenter_nodes_totalrequests_cpu{} + karpenter_nodes_overheads_cpu{}) *100) / karpenter_nodes_allocatable_cpu{}",
     "legendFormat": "Utilization CPU"
    },
    {
     "expr": "((karpenter_nodes_totallimits_cpu{} + karpenter_nodes_overheads_cpu{}) *100) / karpenter_nodes_allocatable_cpu{}",
     "legendFormat": "Overcommitment CPU"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "karpenter_nodes_allocatable_memory{}",
     "legendFormat": "Allocatable Memory"
    },
    {
     "expr": "karpenter_nodes_totalrequests_memory{}",
     "legendFormat": "Requests Memory"
    },
    {
     "expr": "karpenter_nodes_totallimits_memory{}",
     "legendFormat": "Limits Memory"
    },
    {
     "expr": "karpenter_nodes_overheads_memory{}",
     "legendFormat": "Overhead Memory"
    },
    {
     "expr": "((karpenter_nodes_totalrequests_memory{} + karpenter_nodes_overheads_memory{}) *100) / karpenter_nodes_allocatable_memory{}",
     "legendFormat": "Utilization Memory"
    },
    {
     "expr": "((karpenter_nodes_totallimits_memory{} + karpenter_nodes_overheads_memory{}) *100) / karpenter_nodes_allocatable_memory{}",
     "legendFormat": "Overcommitment Memory"
    }
   ]
  }
 ]
}