// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueMetric) DeepCopyInto(out *QueueMetric) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueMetric.
func (in *QueueMetric) DeepCopy() *QueueMetric {
	if in == nil {
		return nil
	}
	out := new(QueueMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalePolicy) DeepCopyInto(out *ScalePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalePolicy.
func (in *ScalePolicy) DeepCopy() *ScalePolicy {
	if in == nil {
		return nil
	}
	out := new(ScalePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalePolicyList) DeepCopyInto(out *ScalePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalePolicyList.
func (in *ScalePolicyList) DeepCopy() *ScalePolicyList {
	if in == nil {
		return nil
	}
	out := new(ScalePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalePolicySpec) DeepCopyInto(out *ScalePolicySpec) {
	*out = *in
	if in.UtilizationMetric != nil {
		in, out := &in.UtilizationMetric, &out.UtilizationMetric
		*out = new(UtilizationMetric)
		**out = **in
	}
	if in.QueueMetric != nil {
		in, out := &in.QueueMetric, &out.QueueMetric
		*out = new(QueueMetric)
		**out = **in
	}
	if in.NodeLabelSelector != nil {
		in, out := &in.NodeLabelSelector, &out.NodeLabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalePolicySpec.
func (in *ScalePolicySpec) DeepCopy() *ScalePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ScalePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalePolicyStatus) DeepCopyInto(out *ScalePolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalePolicyStatus.
func (in *ScalePolicyStatus) DeepCopy() *ScalePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ScalePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UtilizationMetric) DeepCopyInto(out *UtilizationMetric) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UtilizationMetric.
func (in *UtilizationMetric) DeepCopy() *UtilizationMetric {
	if in == nil {
		return nil
	}
	out := new(UtilizationMetric)
	in.DeepCopyInto(out)
	return out
}
