name: InstallHelm
description: 'Installs helm'
inputs:
  version:
    description: "Version of Helm to install"
    required: true
runs:
  using: "composite"
  steps:
    - name: install helm
      shell: bash
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh --version ${{ inputs.version }}
    - name: install helm-diff
      shell: bash
      run: |
        helm plugin install https://github.com/databus23/helm-diff || true