name: InstallHelm
description: 'Installs helm'
inputs:
  version:
    description: "Version of Helm to install"
    required: true
runs:
  using: "composite"
  steps:
    - name: install helm
      shell: bash
      env:
        HELM_VERSION: ${{ inputs.version }}
      run: |
        ./test/hack/e2e_scripts/install_helm.sh
    - name: install helm-diff
      shell: bash
      run: |
        helm plugin uninstall diff || true
        helm plugin install https://github.com/databus23/helm-diff --version v3.9.11 || true