{
 "title": "Karpenter Capacity",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "provisioner",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, provisioner)"
    }
   },
   {
    "name": "zone",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, zone)"
    }
   },
   {
    "name": "arch",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, arch)"
    }
   },
   {
    "name": "capacity_type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, capacity_type)"
    }
   },
   {
    "name": "instance_type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, instance_type)"
    }
   },
   {
    "name": "distribution_filter",
    "query": "arch,capacity_type,instance_type,namespace,node,provisioner,zone"
   }
  ]
 },
 "panels": [
  {
   "title": "Deprovisioning Actions Performed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(action, cluster) (karpenter_deprovisioning_actions_performed)",
     "legendFormat": "{{cluster}}: {{action}}"
    }
   ]
  },
  {
   "title": "Nodes Created",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(cluster) (karpenter_nodes_created)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Nodes Terminated",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(cluster) (karpenter_nodes_terminated)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Pod Phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(phase)(karpenter_pods_state)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pod Distribution: $distribution_filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by ($distribution_filter)(\n    karpenter_pods_state{arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", provisioner=~\"$provisioner\"}\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Provisioner Summary",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "karpenter_provisioner_usage{resource_type=\"cpu\"} / karpenter_provisioner_limit{resource_type=\"cpu\"}",
     "legendFormat": "CPU Limit Utilization"
    },
    {
     "expr": "count by (provisioner)(karpenter_nodes_allocatable{provisioner!=\"N/A\",resource_type=\"cpu\"}) # Selects a single resource type to get node count"
    },
    {
     "expr": "karpenter_provisioner_usage{resource_type=\"memory\"} / karpenter_provisioner_limit{resource_type=\"memory\"}",
     "legendFormat": "Memory Limit Utilization"
    },
    {
     "expr": "sum by (provisioner)(karpenter_nodes_allocatable{provisioner!=\"N/A\",resource_type=\"cpu\"})"
    },
    {
     "expr": "sum by (provisioner)(karpenter_nodes_allocatable{provisioner!=\"N/A\",resource_type=\"memory\"})"
    }
   ]
  },
  {
   "title": "Spot Node Percentage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(count(karpenter_nodes_allocatable{arch=~\"$arch\",capacity_type=\"spot\",instance_type=~\"$instance_type\",provisioner=~\"$provisioner\",zone=~\"$zone\"}) or vector(0)) / count(karpenter_nodes_allocatable{arch=~\"$arch\",instance_type=~\"$instance_type\",provisioner=~\"$provisioner\",zone=~\"$zone\"})",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "((karpenter_nodes_total_daemon_requests{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",provisioner=~\"$provisioner\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0) + \n(karpenter_nodes_total_pod_requests{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",provisioner=~\"$provisioner\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0)) / \nkarpenter_nodes_allocatable{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",provisioner=~\"$provisioner\",zone=~\"$zone\"}",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "((karpenter_nodes_total_daemon_requests{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",provisioner=~\"$provisioner\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0) + \n(karpenter_nodes_total_pod_requests{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",provisioner=~\"$provisioner\",zone=~\"$zone\"} or karpenter_nodes_allocatable*0)) / \nkarpenter_nodes_allocatable{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",provisioner=~\"$provisioner\",zone=~\"$zone\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "karpenter_nodes_total_daemon_requests{resource_type=\"pods\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",provisioner=~\"$provisioner\",zone=~\"$zone\"} + \nkarpenter_nodes_total_pod_requests{resource_type=\"pods\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",provisioner=~\"$provisioner\",zone=~\"$zone\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "label_replace(\n    sum by (node)(node_time_seconds) - sum by (node)(node_boot_time_seconds),\n    \"node_name\", \"$1\", \"node\", \"(.+)\"\n)",
     "legendFormat": "Uptime"
    }
   ]
  }
 ]
}