name: UpgradeCRDs
description: 'Installs Go Downloads and installs Karpenter Dependencies'
inputs:
  account_id:
    description: "Account ID to access AWS"
    required: true
  role:
    description: "Role to access AWS"
    required: true
  region:
    description: "Region to access AWS"
    required: true
  cluster_name:
    description: 'Name of the cluster to be launched by eksctl'
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out. Requires a corresponding Karpenter snapshot release"
runs:
  using: "composite"
  steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
      with:
        role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role }}
        aws-region: ${{ inputs.region }}
        role-duration-seconds: 21600
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        ref: ${{ inputs.git_ref }}
    - name: install-karpenter
      shell: bash
      env:
        CLUSTER_NAME: ${{ inputs.cluster_name }}
      run: |
        aws eks update-kubeconfig --name "$CLUSTER_NAME"
        kubectl apply -f pkg/apis/crds/
