name: InstallKarpenter
description: 'Installs Go Downloads and installs Karpenter Dependencies'
inputs:
  account_id:
    description: "Account ID to access AWS"
    required: true
  role:
    description: "Role to access AWS"
    required: true
  region:
    description: "Region to access AWS"
    required: true
  cluster_name:
    description: 'Name of the cluster to be launched by eksctl'
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out. Requires a corresponding Karpenter snapshot release"
runs:
  using: "composite"
  steps:
  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v2
    with:
      role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role }}
      aws-region: ${{ inputs.region }}
      role-duration-seconds: 21600
  - uses: actions/checkout@v3
    with:
      ref: ${{ inputs.git_ref }}
  - uses: ./.github/actions/e2e/install-helm
  - name: create karpenter namespace
    shell: bash
    run: |
      kubectl create ns karpenter || true
      kubectl label ns karpenter scrape=enabled --overwrite=true
  - name: install-karpenter
    shell: bash
    run: |
      aws eks update-kubeconfig --name ${{ inputs.cluster_name }}
      helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter \
        -n karpenter \
        --version v0.29.0 \
        --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::${{ inputs.account_id }}:role/karpenter-irsa-${{ inputs.cluster_name }}" \
        --set settings.aws.clusterName=${{ inputs.cluster_name }} \
        --set settings.aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-${{ inputs.cluster_name }} \
        --set settings.aws.interruptionQueueName=${{ inputs.cluster_name }} \
        --set controller.resources.requests.cpu=3 \
        --set controller.resources.requests.memory=3Gi \
        --set controller.resources.limits.cpu=3 \
        --set controller.resources.limits.memory=3Gi \
        --set serviceMonitor.enabled=true \
        --set serviceMonitor.additionalLabels.scrape=enabled \
        --wait
  - name: diff-karpenter
    shell: bash
    run: |
      helm diff upgrade --namespace karpenter \
        karpenter oci://public.ecr.aws/karpenter/karpenter \
        --version v0.29.0 \
        --reuse-values --three-way-merge --detailed-exitcode