name: InstallKarpenter
description: 'Installs Go Downloads and installs Karpenter Dependencies'
inputs:
  account_id:
    description: "Account ID to access AWS"
    required: true
  role:
    description: "Role to access AWS"
    required: true
  region:
    description: "Region to access AWS"
    required: true
  cluster_name:
    description: 'Name of the cluster to be launched by eksctl'
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out. Requires a corresponding Karpenter snapshot release"
runs:
  using: "composite"
  steps:
  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role }}
      aws-region: ${{ inputs.region }}
      role-duration-seconds: 21600
  - uses: actions/checkout@v4
    with:
      ref: ${{ inputs.git_ref }}
  - uses: ./.github/actions/e2e/install-helm
  - name: create karpenter namespace
    shell: bash
    run: |
      kubectl create ns karpenter || true
      kubectl label ns karpenter scrape=enabled --overwrite=true
      kubectl label ns karpenter pod-security.kubernetes.io/enforce=restricted --overwrite=true
  - name: install-karpenter
    shell: bash
    run: |
      aws eks update-kubeconfig --name "${{ inputs.cluster_name }}"
      helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter \
        -n karpenter \
        --version "v0-$(git rev-parse HEAD)" \
        --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::${{ inputs.account_id }}:role/karpenter-irsa-${{ inputs.cluster_name }}" \
        --set settings.aws.clusterName="${{ inputs.cluster_name }}" \
        --set settings.aws.defaultInstanceProfile="KarpenterNodeInstanceProfile-${{ inputs.cluster_name }}" \
        --set settings.aws.interruptionQueueName="${{ inputs.cluster_name }}" \
        --set controller.resources.requests.cpu=3 \
        --set controller.resources.requests.memory=3Gi \
        --set controller.resources.limits.cpu=3 \
        --set controller.resources.limits.memory=3Gi \
        --set serviceMonitor.enabled=true \
        --set serviceMonitor.additionalLabels.scrape=enabled \
        --set "serviceMonitor.endpointConfig.relabelings[0].targetLabel=clusterName" \
        --set "serviceMonitor.endpointConfig.relabelings[0].replacement=${{ inputs.cluster_name }}" \
        --set "serviceMonitor.endpointConfig.relabelings[1].targetLabel=gitRef" \
        --set "serviceMonitor.endpointConfig.relabelings[1].replacement=$(git rev-parse HEAD)" \
        --set "serviceMonitor.endpointConfig.relabelings[2].targetLabel=mostRecentTag" \
        --set "serviceMonitor.endpointConfig.relabelings[2].replacement=$(git describe --abbrev=0 --tags)" \
        --set "serviceMonitor.endpointConfig.relabelings[3].targetLabel=commitsAfterTag" \
        --set "serviceMonitor.endpointConfig.relabelings[3].replacement=\"$(git describe --tags | cut -d '-' -f 2)\"" \
        --wait
  - name: diff-karpenter
    shell: bash
    run: |
      helm diff upgrade --namespace karpenter \
        karpenter oci://public.ecr.aws/karpenter/karpenter \
        --version v0-$(git rev-parse HEAD) \
        --reuse-values --three-way-merge --detailed-exitcode