name: InstallKarpenter
description: 'Installs Go Downloads and installs Karpenter Dependencies'
inputs:
  account_id:
    description: "Account ID to access AWS"
    required: true
  role:
    description: "Role to access AWS"
    required: true
  region:
    description: "Region to access AWS"
    required: true
  ecr_account_id:
    description: "Account ID for the ECR repo"
    required: true
  ecr_region:
    description: "Region for the ECR repo"
    required: true
  cluster_name:
    description: 'Name of the cluster to be launched by eksctl'
    required: true
  k8s_version:
    description: 'Version of Kubernetes to use for the launched cluster'
    default: "1.35"
  git_ref:
    description: "The git commit, tag, or branch to check out. Requires a corresponding Karpenter snapshot release"
  private_cluster:
    description: "Whether the cluster is private or not. Valid values are 'true' or 'false'"
    default: 'false'
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    with:
      ref: ${{ inputs.git_ref }}
  - uses: ./.github/actions/e2e/install-helm
    with:
      version: v3.18.6
  # Label namespace to enforce security stranded and scrape prometheus metrics
  # https://kubernetes.io/docs/concepts/security/pod-security-standards/
  - name: add labels to kube-system namespace
    shell: bash
    run: |
      kubectl label ns kube-system scrape=enabled --overwrite=true
      kubectl label ns kube-system pod-security.kubernetes.io/warn=restricted --overwrite=true
  - name: login to ecr via docker
    uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
    with:
      registry: ${{ inputs.ecr_account_id }}.dkr.ecr.${{ inputs.ecr_region }}.amazonaws.com
      logout: true
  - name: install-karpenter
    shell: bash
    env:
      ECR_ACCOUNT_ID: ${{ inputs.ecr_account_id }}
      ECR_REGION: ${{ inputs.ecr_region }}
      ACCOUNT_ID: ${{ inputs.account_id }}
      CLUSTER_NAME: ${{ inputs.cluster_name }}
      PRIVATE_CLUSTER: ${{ inputs.private_cluster }}
    run: |
      output=$(./test/hack/e2e_scripts/install_karpenter.sh 2>&1)
      if echo "$output" | grep -i "warning.*violate.*podsecurity"; then
        echo "ERROR: Karpenter does not respect restricted Pod Security Standard"
        exit 1
      fi
  - name: diff-karpenter
    shell: bash
    env:
      ECR_ACCOUNT_ID: ${{ inputs.ecr_account_id }}
      ECR_REGION: ${{ inputs.ecr_region }}
    run: |
      ./test/hack/e2e_scripts/diff_karpenter.sh
