apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuron
spec:
  replicas: 0
  selector:
    matchLabels:
      app: neuron
  template:
    metadata:
      labels:
        app: neuron
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
        name: neuron
        resources:
          limits:
            aws.amazon.com/neuron: "1"
          requests:
            cpu: "1"
            memory: 256M
        securityContext:
          allowPrivilegeEscalation: false
