name: DumpLogs
description: 'Dump logs and debug information from the cluster after a test run'
inputs:
  account_id:
    description: "Account ID to access AWS"
    required: true
  role:
    description: "Role to access AWS"
    required: true
  region:
    description: "Region to access AWS"
    required: true
  cluster_name:
    description: 'Name of the cluster to be launched by eksctl'
    required: true
runs:
  using: "composite"
  steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
      with:
        role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role }}
        aws-region: ${{ inputs.region }}
        role-duration-seconds: 21600
    - name: update cluster context
      shell: bash
      env:
        CLUSTER_NAME: ${{ inputs.cluster_name }}
      run: |
        aws eks update-kubeconfig --name "$CLUSTER_NAME"
    - name: controller-logs
      shell: bash
      run: |
        kubectl logs -n kube-system -l app.kubernetes.io/name=karpenter --all-containers --ignore-errors
    - name: describe karpenter pods
      shell: bash
      run: |
        kubectl describe pods -n kube-system -l app.kubernetes.io/name=karpenter
    - name: describe nodes
      shell: bash
      run: |
        kubectl describe nodes
