apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kwok-karpenter-extra
rules:
  - apiGroups: [""]
    resources: ["configmaps", "nodes"]
    verbs: ["get", "watch", "list", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kwok-karpenter-extra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kwok-karpenter-extra
subjects:
  - kind: ServiceAccount
    name: kwok-karpenter
    namespace: $KARPENTER_NAMESPACE