name: DryRunGen
on:
  push:
    branches:
      - 'main'
      - 'release-v*'
      - 'staging/*'
jobs:
  dryrun-gen:
    permissions:
      id-token: write # aws-actions/configure-aws-credentials@v4.0.1
    if: github.repository == 'aws/karpenter-provider-aws'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/install-deps
        with:
          use-cache: false
      - uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6.2.2
        with:
          role-to-assume: 'arn:aws:iam::${{ vars.READONLY_ACCOUNT_ID }}:role/${{ vars.READONLY_ROLE_NAME }}'
          aws-region: ${{ vars.READONLY_REGION }}
      - run: make docgen
      - run: make codegen
        env:
          ENABLE_GIT_PUSH: false
      - run: make prepare-website
        env:
          GIT_TAG: v0.10000.0 # Mock version for testing website generation
